README.md

Add a description to the README file

---

CONTRIBUTORS.md

added contributors file

---

LICENSE.md

Add LICENSE file #6

---

README.md

fix #15 add git command to the readme file

Adding git commands to readme

---

.gitignore

Add .gitignore file containing ".vagrant" as files to ignore

---

.gitignore

adding git ignore file with .idea and nohup

---

Vagrantfile
bootstrap.sh

Hi Liora,
I created new PR for adding the Bootstrap.sh file and also the changes in the Vagrant file.
I did them on a new Branch name roypr as you mentioned that we will not use the master branch for any new PR. 
Let me know in any issue,
Thanks,
Roy

Adding bootstrap.sh script for VM os upgrade

---

.travis.yml
bootstrap.sh

Issue27 fix

---

Vagrantfile

Changing configs to Ubuntu box

---

README.md

virtualenvwrapper documentation added to README

---

bootstrap.sh

added installation of pip3 to bootstrap.sh

---

bootstrap.sh

added flask installation to bootstrap.sh

---

Vagrantfile

Changed Vagrant box to Ubunto/bento-18

---

.travis.yml
bootstrap.sh

added flake8 install and execution of it from .travis

---

app.py

Adding Flask App file

---

.travis.yml

Refactor .travis to better reflect the flow order

---

Vagrantfile

Added port-forwarding (5000) to Vagrantfile

---

bootstrap.sh

Executing flask app in the background

---

bootstrap.sh

changed to python3

---

bootstrap.sh

pip3 install from requirements.txt

---

.travis.yml
tests/http_get_test.sh

 Added HTTP get test to CI

---

tests/http_get_test.sh

fix #78  
might fix Travis test failure, as described in #77

fixed http_get_test to work on Ubuntu machine

---

bootstrap.sh

adding custom path for the requirements

---

app.py
templates/home.html

additg render_template html file

---

templates/home.html

Added bootstrap support to the HTML file

---

templates/home.html

adding bootstrap navbar

---

app.py

Adding Debug to flask app.run

---

README.md
bootstrap.sh

Installed mySQL on the machine and added users table

---

.travis_backwq.yml

Deprecate Travis CI

---

.github/workflows/main.yml
requirements.txt
tests/test_sanity.py

fix #105 
**Please NOTE. the CI is expected to fail. Since the mysql server failing to run on the CI**
See issue "bootstrap.sh - fix sql script"
https://github.com/knowabli/baboon/issues/99

introducing pytest - mysql test and webserver test

---

requirements.txt

Add aws python package (version 0.2.5)

---

bootstrap.sh

fix #118  by installing p3 setuptools on bootstrap

Fix CI failure

---

Vagrantfile

Modify Vagrant file to support 'dev' and 'stage' envs

---

requirements.txt

added boto3 to requirements

---

bootstrap-infra.py
requirements.txt

added script for managing security group

---

.github/workflows/main.yml

fix #130 
If this fix is working, it should probably fail the CI...
Edit: yay, it does.

Flake8 tests errors fail the CI

---

requirements.txt
requirements_infra.txt

Split the requirements file into infra and app

---

README.md

Fix #33 and Fix #129 
I added 3 commands and descriptions, and also redesign the previous documentation to use the README style better.

Add documentation about vagrant commands and isort to README.md 

---

.github/workflows/main.yml
baboon/__init__.py

Fixed indentation, which caused CI to fail on syntax error

---

baboon/__init__.py

Fixed issue for #151 by adding 'from baboon import routes' to baboon/__init__.py

---

beyond/templates/home.html
beyond/templates/layout.html
tests/functional/test_title.py

Adding some more updates for changing Baboon (Capital "B") to Beyond.

Adding some more updates for Baboon change to Beyond code Issue #157

---

beyond/templates/home.html
beyond/templates/layout.html

Hi . 
Home page content is updated + i fixed the linked for the other page as to the high level topics we agreed.
I also removed housmade legacy content (-: 
Please review and approved. 
Thanks!

Add content to html Home page and the main page links

---

.env_template

Following Issue - Add guidelines to the .env_template file #163

Adding Comments to make the values in this file more friendly to consume. 

---

beyond/routes.py
beyond/templates/contacts.html
beyond/templates/layout.html
tests/functional/test_title.py

Adding some content to 'contacts' page, removing obsolete tabs from home page + adding TC for contacts page

---

Vagrantfile
bootstrap.sh
tests/requirements-test.txt
tests/test_sanity.py

fix #175 
added test for docker
added dependency for using pystemd
added docker installation
added pystemd 0.8.0 as a dependency

Install docker inside Vagrant VM, and add a test that it is running

---

.github/workflows/main.yml

Hardcoding the ubuntu version to 18.04 in github flow.

---

Dockerfile

#176 
Adding Dockerfile to the project root folder to run Ubuntu 18.04 and Python3.

Adding Dockerfile with Unubtu 18:04 and Python3

---

bootstrap.sh

close #192 
Redirecting the output of the python command to a file, include the stderr and stdout.
This way we will have a logging file to monitor and see future errors.
The file will be created under the /vagrant folder

added redirection for stderr and stdout to a file

---

beyond/templates/layout.html

Fixing the favicon of our webapp html

---

.dockerignore

Cleaning up dockerignore file to include only app critical stuff

---

beyond/routes.py
beyond/templates/cycles.html
beyond/templates/layout.html
tests/functional/test_title.py

Adding 'cycles' page + webdriver test for it

---

Dockerfile
docker-compose.yml
requirements.txt
tests/test_sanity.py

fix #219 
Test added to check whether it is running. Requirements updated along
with Docker file

Adding PostgreSQL as a separate container to use as a DB with our app
